rootString = "Hello, world!"
[main]
int = 42 # test comment
float = 21.0 # test comment
[main.sub]
bool = true# test comment
[test]
salut = "c'est\\\\\n\t\t\"Fanta\""    	
coucou = "How \u20AC are \t you \u00bf"
[test.a.b.c]
[test.a]
# simple = [0, 1, 2]
# less-simple = [ [0, 1, 2], [3, 4, 5] ]
# wtf = [ [[0, 1], [2, 3]], [[4, 5], [6, 7]] ]
[test.a.b]
bool = false	
